application: pour-over
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: off
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: lxml
  version: "2.3"

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico
  secure: always

- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt
  secure: always

- url: (^/$)
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /(.*\.(css|png|html|js))
  static_files: static/\1
  upload: static/(.*\.(css|png|html|js))
  secure: always

- url: .*
  script: run.application.app
  secure: always