application: adn-pourover
module: default
version: duo
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5m"

builtins:
- appstats: on
- admin_redirect: off
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: lxml
  version: "2.3"

inbound_services:
- warmup
- mail

instance_class: F1
automatic_scaling:
  max_idle_instances: 1
  min_pending_latency: 10.0s

includes:
- yaml/handlers.yaml